[versions]
# Kotlin / Android Plugin
detektApi = "1.23.6"
kotlin = "1.9.24"
agp = "8.8.0"

# Core & AndroidX
coreKtxVersion = "1.13.1"
appcompat = "1.7.1"
material = "1.12.0"

# JUnit & Mockito
junitVersion = "4.13.2"
junitJupiterVersion = "5.10.2"
junitVintageEngine = "5.10.1"
mockitoCore = "5.15.2"
mockitoAndroid = "5.12.0"

# AspectJ
aspectjrt = "1.9.19"
aspectjtools = "1.9.19"

# Logging
logbackAndroid = "3.0.0"
slf4jApi = "2.0.16"

# Build & Tools
desugar_jdk_libs = "2.1.5"

# Misc
espressoCore = "3.6.1"
androidxJunit = "1.2.1"
runner = "1.6.2"
monitor = "1.8.0"

#KSP
kotlinpoet = "1.15.1"
ksp = "1.9.24-1.0.20"
agpVersion = "8.8.0"
kotlinVersion = "1.9.24"
appcompatVersion = "1.7.1"

[plugins]
# 統一したプラグイン定義
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-library = { id = "com.android.library", version.ref = "agpVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }


[libraries]
core-ktx-v1131 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detektApi" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detektApi" }
material = { module = "com.google.android.material:material", version.ref = "material" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

# テスト系
junit = { module = "junit:junit", version.ref = "junitVersion" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiterVersion" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junitVintageEngine" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroid" }

# AspectJ
aspectjrt = { module = "org.aspectj:aspectjrt", version.ref = "aspectjrt" }
aspectjtools = { module = "org.aspectj:aspectjtools", version.ref = "aspectjtools" }
# AspectJ Weaver (for testing)
aspectjweaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectjrt" }

# Logging
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logbackAndroid" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }

# Build Tools
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

# AndroidX Testing
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
monitor = { module = "androidx.test:monitor", version.ref = "monitor" }

# KotlinPoet 系ライブラリ
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }

