@startebnf
'https://plantuml.com/mindmap-diagram

caption figure 1
title AndrORM 構文チェック図

header My super header endheader

Any = ("column" | "value");

select_single_column_syntax = select, "column",from_after_syntax;

select_multiple_column_syntax = select, {"column"}-,from_after_syntax;

from_after_syntax =  from, "table",
                    [[inner | left | right | full], "table", {join_condition}] ,
                    [where, condition, {(and | or), condition}],
                    [group_by,{"column"}-],
                    [order_by, {"column"}- ];

join_condition = on, condition;

condition = (Any, (eq | lt | le | ge | gt | not_eq), Any |
            ("column", in, ({Any}- | select_single_column_syntax))) |
            (exists, (select_single_column_syntax | select_multiple_column_syntax)) ;

center footer My super footer

@endebnf
