package jp.pgw.lab78.androrm.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo
import jp.pgw.lab78.androrm.common.SupportFunction.toSnakeCase

/**
 * ## AndrORM プロパティプロセッサクラス
 * ### AndrORM の標準アノテーションを基に
 * ### プロパティ一覧、データクラス、インターフェース一覧を作成
 * ### PropsProcessorProvider#create(SymbolProcessorEnvironment) から呼び出される
 * @param codeGenerator コード生成時に出力機能を提供
 * @param logger ビルド中の経過、警告、エラー等の情報を出力する環境を提供
 */
class PropsProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    /**
     * ## AndrORM アノテーションプロセスメソッド
     * ### AndrORM で定義されているアノテーションを解析し
     * ### プロパティ一覧、データクラス、インターフェース一覧を作成し
     * ### Kotlin ファイルを生成する
     * @param resolver アノテーション解析機能を提供
     * @return 解析に失敗したシンボル
     * @see SymbolProcessor.process
     */
    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation("jp.pgw.lab78.androrm.ksp.annotation.GenerateProps")
        val classDecls = symbols.filterIsInstance<KSClassDeclaration>()
        classDecls.forEach { classDecl ->
            // Props 生成
            generateProps(classDecl)

            // Projection 生成
            generateProjections(classDecl)
        }
        return emptyList()
    }

    /**
     * ## プロパティ一覧生成メソッド
     * ### @GenerateProps を抽出しプロパティ一覧を
     * ### Kotlin ファイルとして出力する
     * @param classDecl Kotlin のクラス宣言を表す KSP シンボル
     */
    private fun generateProps(classDecl: KSClassDeclaration) {
        val className = classDecl.simpleName.asString()
        val pkg = classDecl.packageName.asString()
        val propsName = "${className.removeSuffix("Entity")}Props"
        // ログ出力
        logger.info(">>> Processing class: $className in $pkg")
        // クラス情報から全てのプロパティを抽出
        val props = classDecl.getAllProperties().map {
            it.simpleName.asString()
        }
        // クラス情報から全てのプロパティを抽出
        val fileSpec = FileSpec.builder(pkg, propsName)
            // object クラスの追加
            .addType(
                TypeSpec.objectBuilder(propsName).addModifiers(KModifier.PUBLIC).apply {
                    props.forEach { prop ->
                        // property の追加
                        addProperty(
                            PropertySpec.builder(prop.toSnakeCase(), String::class, KModifier.CONST)
                                .initializer("%S", prop)
                                .build()
                        )
                    }
                }.build())
            // コメント
            .addFileComment("Generated by AndrORM")
            .build()
        val fileDependency = classDecl.containingFile?.let { Dependencies(true, it) } ?: Dependencies(false)
        fileSpec.writeTo(codeGenerator, fileDependency)
    }

    /**
     * ## データクラス生成メソッド
     * ### @Projection と @Projections を抽出しデータクラスを
     * ### Kotlin ファイルとして出力する
     * @param classDecl Kotlin のクラス宣言を表す KSP シンボル
     */
    private fun generateProjections(classDecl: KSClassDeclaration) {
        val projections = mutableListOf<Pair<String, List<KSPropertyDeclaration>>>()
        for (ann in classDecl.annotations) {
            val annotationName = ann.annotationType.resolve().declaration.qualifiedName?.asString()
            // @Projection の抽出
            if (annotationName == "jp.pgw.lab78.androrm.ksp.annotation.Projection") {
                val name = ann.arguments.find { it.name?.asString() == "entityNameExtend" }?.value as? String ?: continue
                val fields = (ann.arguments.find { it.name?.asString() == "fields" }?.value as? List<*>)
                    ?.mapNotNull { it as? String } ?: continue
                val selectedProps = classDecl.getAllProperties()
                    .filter { fields.contains(it.simpleName.asString()) }
                    .toList()
                // ログ出力
                logger.info(">>> Processing class: $name in $selectedProps")
                // @Projection から抽出した「エンティティ名拡張文字列」と「抽出プロパティ」を Map に格納
                projections.add(name to selectedProps)
            }
            if (annotationName == "jp.pgw.lab78.androrm.ksp.annotation.Projections") {
                val value = ann.arguments.find { it.name?.asString() == "value" }?.value
                val projectionAnnotations = (value as? List<*>)?.mapNotNull { it as? KSAnnotation } ?: continue

                for (projectionAnn in projectionAnnotations) {
                    val name = projectionAnn.arguments.find { arg -> arg.name?.asString() == "entityNameExtend" }?.value as? String ?: continue
                    val fields = (projectionAnn.arguments.find { arg -> arg.name?.asString() == "fields" }?.value as? List<*>)
                        ?.mapNotNull { it as? String } ?: continue

                    val selectedProps = classDecl.getAllProperties()
                        .filter { fields.contains(it.simpleName.asString()) }
                        .toList()

                    projections.add(name to selectedProps)
                }
            }
        }

        val pkg = classDecl.packageName.asString()
        val originalName = classDecl.simpleName.asString()

        for ((name, props) in projections) {
            val projectionClassName = "${originalName}${name}"
            logger.info(">>> Processing class: $projectionClassName")
            val typeSpec = TypeSpec.classBuilder(projectionClassName)
                .addModifiers(KModifier.DATA)
                .primaryConstructor(
                    FunSpec.constructorBuilder()
                        .apply {
                            logger.info(">>> Processing class: $projectionClassName in $props")
                            for (prop in props) {
                                val type = prop.type.resolve().toTypeName()
                                addParameter(prop.simpleName.asString(), type)
                            }
                        }
                        .build()
                )
                .apply {
                    logger.info(">>> Processing class: $projectionClassName in $props")
                    for (prop in props) {
                        val type = prop.type.resolve().toTypeName()
                        addProperty(
                            PropertySpec.builder(prop.simpleName.asString(), type)
                                .initializer(prop.simpleName.asString())
                                .build()
                        )
                    }
                }
                .build()

            val fileSpec = FileSpec.builder(pkg, projectionClassName)
                .addType(typeSpec)
                .build()
            val fileDependency = classDecl.containingFile?.let { Dependencies(true, it) } ?: Dependencies(false)
            fileSpec.writeTo(codeGenerator, fileDependency)
            logger.info(">>> Generated Projection Class: $projectionClassName")
        }
    }

}

/**
 * ## プロパティプロセッサ提供元クラス
 * ### ビルドツールから呼び出され、プロパティプロセッサのインスタンスを
 * ### ビルドツールに戻す
 */
class PropsProcessorProvider : SymbolProcessorProvider {

    /**
     * ## プロパティプロセッサ生成メソッド
     * ### プロパティプロセッサのインスタンスを生成する
     * @param environment シンボルプロセッサ環境（ビルドツールから渡される）
     * @return 生成されたプロパティプロセッサのインスタンス
     * @see SymbolProcessorProvider.create
     */
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return PropsProcessor(environment.codeGenerator, environment.logger)
    }
}
