@startuml
title shared-library ユースケース図
skinparam shadowing false
skinparam roundcorner 8
skinparam linetype ortho
skinparam packageStyle rectangle
skinparam componentStyle rectangle
skinparam defaultTextAlignment left
skinparam noteBackgroundColor #FFFDE7
skinparam noteBorderColor #9E9E9E
skinparam ArrowColor #455A64
skinparam activityDiamondBackgroundColor #ECEFF1
skinparam activityDiamondBorderColor #455A64

left to right direction
actor "app debug AOP" as App
actor "androrm-common logging" as Common
actor "KSP logging" as KSP

rectangle "shared-library" {
  usecase "nullを判定する" as U1
  usecase "Unitを判定する" as U2
  usecase "void型を判定する" as U3
}

App --> U1
App --> U2
App --> U3
Common --> U1
KSP --> U1

@enduml
